# -*- coding: utf-8 -*-
"""Tampus_SeatworkRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFGzwZ9w_bGrnrKC_BUkS8ksP5HU3vQy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

data = pd.read_csv('../datasets/SeatworkData.csv')

# Display the Data from CSV
pd.set_option('display.max_rows', None)  # Display all rows
print(data)

X = data[['Market Capitalization ($million) x']]
y = data['Profits ($million) y']

model = LinearRegression()
model.fit(X, y)

y_prediction = model.predict(X)

#Print the coefficients for reg model
print("Coefficients: \n", model.coef_)
print("Intercept: \n", model.intercept_)

# MSE, MAE, R2
mse = mean_squared_error(y, y_prediction)
mae = mean_absolute_error(y, y_prediction)
r2 = r2_score(y, y_prediction)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R-squared: {r2}")

coefficient = model.coef_[0]
intercept = model.intercept_
regression_equation = f"Estimated regression model: Profit = {coefficient:.2f} * Market Capitalization + {intercept:.2f}"
print(regression_equation)

# Display Chart Results
plt.scatter(X, y, color='blue')
plt.plot(X, y_prediction, color='red', linewidth=2)
plt.xlabel('Market Capitalization ($million) x')
plt.ylabel('Profits ($million) y')
plt.title('Linear Regression')
plt.grid(True)
plt.show()

